const i18n = {
    en: {
        title: "TechMC Glossary Search",
        placeholder: "Keywords...",
        short: "Short Form",
        fullEnglish: "Full Form (English)",
        full: " ",
        desc: "Description",
        noResult: "No Result",
        noShort: "No Short Form",
        noFullEnglish: "No English FullForm",
        noFull: " ",
        noDesc: "No Description",
        lang: "English"
    },
    zh: {
        title: "TechMC术语查询",
        placeholder: "输入关键词...",
        short: "缩写",
        fullEnglish: "英文全称",
        full: "全称",
        desc: "描述",
        noResult: "没有结果",
        noShort: "无缩写",
        noFullEnglish: "无英文全称",
        noFull: "无全称",
        noDesc: "无描述",
        lang: "Chinese"
    },
    ar: {
        title: "بحث مسرد TechMC",
        placeholder: "الكلمات المفتاحية...",
        short: "اختصار",
        fullEnglish: "الاسم الكامل (إنجليزي)",
        full: "الاسم الكامل (عربي)",
        desc: "الوصف",
        noResult: "لا توجد نتائج",
        noShort: "لا يوجد اختصار",
        noFullEnglish: "لا يوجد اسم كامل بالإنجليزية",
        noFull: "لا يوجد اسم كامل",
        noDesc: "لا يوجد وصف",
        lang: "Arabic"
    },
    fr: {
        title: "Recherche du glossaire TechMC",
        placeholder: "Mots-clés...",
        short: "Abréviation",
        fullEnglish: "Forme complète (Anglais)",
        full: "Forme complète (Français)",
        desc: "Description",
        noResult: "Aucun résultat",
        noShort: "Pas d'abréviation",
        noFullEnglish: "Pas de forme complète en anglais",
        noFull: "Pas de forme complète",
        noDesc: "Pas de description",
        lang: "French"
    },
    de: {
        title: "TechMC Glossar Suche",
        placeholder: "Stichwörter...",
        short: "Abkürzung",
        fullEnglish: "Vollständige Form (Englisch)",
        full: "Vollständige Form (Deutsch)",
        desc: "Beschreibung",
        noResult: "Keine Ergebnisse",
        noShort: "Keine Abkürzung",
        noFullEnglish: "Keine englische Vollform",
        noFull: "Keine Vollform",
        noDesc: "Keine Beschreibung",
        lang: "German"
    },
    it: {
        title: "Ricerca glossario TechMC",
        placeholder: "Parole chiave...",
        short: "Abbreviazione",
        fullEnglish: "Forma completa (Inglese)",
        full: "Forma completa (Italiano)",
        desc: "Descrizione",
        noResult: "Nessun risultato",
        noShort: "Nessuna abbreviazione",
        noFullEnglish: "Nessuna forma completa in inglese",
        noFull: "Nessuna forma completa",
        noDesc: "Nessuna descrizione",
        lang: "Italian"
    },
    ja: {
        title: "TechMC用語検索",
        placeholder: "キーワード...",
        short: "略語",
        fullEnglish: "完全な形（英語）",
        full: "完全な形（日本語）",
        desc: "説明",
        noResult: "結果なし",
        noShort: "略語なし",
        noFullEnglish: "英語の完全な形なし",
        noFull: "完全な形なし",
        noDesc: "説明なし",
        lang: "Japanese"
    },
    ko: {
        title: "TechMC 용어 검색",
        placeholder: "키워드...",
        short: "약어",
        fullEnglish: "전체 형식 (영어)",
        full: "전체 형식 (한국어)",
        desc: "설명",
        noResult: "결과 없음",
        noShort: "약어 없음",
        noFullEnglish: "영어 전체 형식 없음",
        noFull: "전체 형식 없음",
        noDesc: "설명 없음",
        lang: "Korean"
    },
    pt: {
        title: "Pesquisa no glossário TechMC",
        placeholder: "Palavras-chave...",
        short: "Abreviação",
        fullEnglish: "Forma completa (Inglês)",
        full: "Forma completa (Português)",
        desc: "Descrição",
        noResult: "Sem resultados",
        noShort: "Sem abreviação",
        noFullEnglish: "Sem forma completa em inglês",
        noFull: "Sem forma completa",
        noDesc: "Sem descrição",
        lang: "Portugese"
    },
    ru: {
        title: "Поиск в глоссарии TechMC",
        placeholder: "Ключевые слова...",
        short: "Аббревиатура",
        fullEnglish: "Полная форма (Английский)",
        full: "Полная форма (Русский)",
        desc: "Описание",
        noResult: "Нет результатов",
        noShort: "Нет аббревиатуры",
        noFullEnglish: "Нет полной формы на английском",
        noFull: "Нет полной формы",
        noDesc: "Нет описания",
        lang: "Russian"
    },
    es: {
        title: "Búsqueda de Glosario TechMC",
        placeholder: "Palabras clave...",
        short: "Abreviatura",
        fullEnglish: "Forma completa (Inglés)",
        full: "Forma completa (Español)",
        desc: "Descripción",
        noResult: "Sin resultados",
        noShort: "Sin abreviatura",
        noFullEnglish: "Sin forma completa en inglés",
        noFull: "Sin forma completa",
        noDesc: "Sin descripción",
        lang: "Spanish"
    }
};
